### ISSUE TITLE
Could we have just a TINY bit of documentation? :)

### ISSUE THREAD

**Issue by srfoster** [wtfaremyinitials/minecraft-schematic#1]
I think this project has exactly what I'm looking for: I need to be able to deal with Minecraft schematic files in the browser.  But it's pretty hard for me to reverse engineer it and figure out the intended usage.  

Even just a tiny bit of "Getting started" material would literally make me weep tears of joy.  :)

**Comment by wtfaremyinitials** [comment]
I'd be happy to write out some documentation! I'm in the middle of taking finals, so I can get to it in a week or so. :smiley:

**Comment by wtfaremyinitials** [comment]
Fixed with ee9036d. Feel free to reopen if you need further help and/or clarification. @srfoster
